### ISSUE TITLE
Update BEL namespace export with bel-resources 0.0.3

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/famplex#110]
The BEL namespace (.belns) export of FamPlex is slightly different when exported using bel-resources 0.0.2 vs 0.0.3. The current master uses 0.0.2 for the export. There are two differences: (1) no blank lines vs having blank lines between sections, and (2) the order of entity types being `GRPC` vs `CGPR`. @cthoyt, is it safe to update the export to use the bel-resources 0.0.3 format?

**Comment by cthoyt** [comment]
Yes it’s safe. These are both purely cosmetic
