### ISSUE TITLE
Invalid entry name

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/famplex#150]
In https://github.com/sorgerlab/famplex/pull/148, we added an entry called `Paf1/RNA_polymerase_II_complex`, which is technically not valid under the `^[a-zA-Z0-9][A-Za-z0-9_]+$` pattern at https://registry.identifiers.org/registry/fplx and so we won't be able to link to it. @steppi is there an alternative name we could change it to?

**Comment by steppi** [comment]
I see, I should have caught that. I imported this one from [HGNC group 1029](https://www.genenames.org/data/genegroup/#!/group/1029) and this was the name that was automatically generated by the import script. Paf1_RNA_polymerase_II_complex would be fine, or PAF1_complex to be less verbose. There's literature support for the shorter name, [here](https://www.pnas.org/content/115/40/9998) for instance.
