### ISSUE TITLE
Identifiers.org links to BioPortal are broken

### ISSUE THREAD

**Issue by bgyori** [sorgerlab/famplex#163]
I feel like this has happened before but FamPlex identifiers.org links don't seem to work currently. The full link for e.g., `PKN` on BioPortal is 
```
https://bioportal.bioontology.org/ontologies/FPLX/?
p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFPLX_PKN
```
and `https://identifiers.org/fplx:PKN` redirects to
```
https://bioportal.bioontology.org/ontologies/FPLX/?
p=classes&conceptid=http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FFPLX_PKN
```
This is the pattern from the identifiers.org registry: 
```
http://bioportal.bioontology.org/ontologies/FPLX/?
p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFPLX_{$id}
```

It looks like identifiers.org is escaping the % sign in the pattern maybe?

**Comment by bgyori** [comment]
Filed an issue at https://github.com/identifiers-org/identifiers-org.github.io/issues/144

**Comment by cthoyt** [comment]
Thoughts on autogenerating a website for FamPlex and just switching to that? We could reuse the code that makes the CONSO pages https://pharmacome.github.io/conso/

**Comment by bgyori** [comment]
Yes, I think something along those lines, i.e., an auto-generated Github page kept up to date using a Github action would be great. It seems like it would be straightforward to auto-generate pages, especially now that the resources can also be accessed through a Python API. Since @johnbachman may have some pre-existing work for a website, we could see if that should be revisited or if we could start from scratch.
