### ISSUE TITLE
Add static site generator

### ISSUE THREAD

**Issue by cthoyt** [sorgerlab/famplex#164]
1. @cthoyt Implement a static site generator, similar to what's available for CONSO ([code](https://github.com/pharmacome/conso), [site](https://pharmacome.github.io/conso/))
2. @bgyori turn on GitHub pages for this repository, serving from main branch `docs/` directory (that's a canned setting)
3. Consider improvements to curation to make site more interesting:
  - More descriptions
  - Reference information for synonyms
  - Classification of entities as complexes, families, or famplexes
  - Lookup of names for xrefs and entities in relations with PyOBO

**Comment by bgyori** [comment]
- More descriptions: Yes, that would be useful, even if brief
- Reference information for synonyms: do you mean like an example PMID where a given synonym is used? That could be useful though it requires additional curation effort and we may have to introduce a new resource file for that info.
- Classification of entities: I think this classification can be automatically inferred from membership so I'm not sure if it should be something that is curated/modifiable or something that is displayed on e.g., the website but is determined automatically based on an entry's children.
- Lookup of names for xrefs: would be good for display purposes as long as it doesn't cause too many complications with extra dependencies and resource files

**Comment by cthoyt** [comment]
@bgyori yup, all could be done in time. I could automate getting descriptions of some elements based on their xrefs. I made a new issue for classificaitons, and it would be quite cool to get some reference information from where the synonym was used!

Let's put the xrefs lookup for later, since this will introduce many requirements.
