### ISSUE TITLE
Add mappings to Signor Families and Complexes

### ISSUE THREAD

**Issue by johnbachman** [sorgerlab/famplex#25]
The Signor curators created their own taxonomy of protein families and complexes, along with their members. Would be useful to have mappings to this resource as well.

**Comment by johnbachman** [comment]
Many of these were handled in 37538551b3e47f. However, before closing, should add mappings for protein families 31-35, which are included in latest Signor corpus but not mapped.

**Comment by bgyori** [comment]
Currently, `SIGNOR-PF36` to `SIGNOR-PF50` are unmapped.

**Comment by steppi** [comment]
I'll take care of this.

**Comment by bgyori** [comment]
Thanks!
